# Generated by Django 6.0.7 on 2026-09-18 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ชื่อสถานที่/วัด')),
                ('category', models.CharField(default='วัด/ศาสนสถาน', max_length=100, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('highlight', models.CharField(blank=True, max_length=255, verbose_name='จุดเด่นไฮไลท์')),
                ('image', models.CharField(default='1.png', max_length=255, verbose_name='รูปภาพประกอบ')),
                ('latitude', models.FloatField(default=15.1186, verbose_name='ละติจูด')),
                ('longitude', models.FloatField(default=104.322, verbose_name='ลองจิจูด')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='ที่อยู่/ตำบล')),
                ('opening_hours', models.CharField(default='08:00 - 17:00 น.', max_length=100, verbose_name='เวลาเปิด-ปิด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='category',
            field=models.CharField(default='วัด/ศาสนสถาน', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='latitude',
            field=models.FloatField(default=15.1186),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='longitude',
            field=models.FloatField(default=104.322),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.place'),
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.reviewcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.reviewcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'review')},
            },
        ),
    ]
