# Generated by Django 6.0.7 on 2026-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_place_reviewcomment_category_reviewcomment_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='รูปภาพแนบ'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='รูปภาพแนบในคอมเมนต์ย่อย'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='category',
            field=models.CharField(default='จุดท่องเที่ยวหลัก', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='latitude',
            field=models.FloatField(default=13.7466),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='longitude',
            field=models.FloatField(default=100.5347),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='photo_title',
            field=models.CharField(blank=True, default='สถานที่ท่องเที่ยว', max_length=200, null=True),
        ),
    ]
