# Generated by Django 6.0.7 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewcomment_image_reviewreply_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='image2',
            field=models.TextField(blank=True, null=True, verbose_name='รูปภาพแนบ 2'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='image3',
            field=models.TextField(blank=True, null=True, verbose_name='รูปภาพแนบ 3'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='image4',
            field=models.TextField(blank=True, null=True, verbose_name='รูปภาพแนบ 4'),
        ),
    ]
